# Number windows and panes from 1
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Improve terminal application responsiveness
set -sg escape-time 0
set -g focus-events on

# Enable mouse selection and resizing
set -g mouse on

# Bright active pane border
set -g pane-active-border-style 'fg=brightcyan,bold'

# Create a window in the current pane's directory
bind c new-window -c "#{pane_current_path}"

# Neovim-style splitting, preserving the current directory
bind s split-window -h -c "#{pane_current_path}"
bind S split-window -v -c "#{pane_current_path}"

# Name each window after the active pane's current directory
set-window-option -g automatic-rename on
set-window-option -g automatic-rename-format "#{b:pane_current_path}"

# Seamless navigation between tmux panes and Neovim windows
bind-key -n C-h if -F "#{@pane-is-vim}" "send-keys C-h" "select-pane -L"
bind-key -n C-j if -F "#{@pane-is-vim}" "send-keys C-j" "select-pane -D"
bind-key -n C-k if -F "#{@pane-is-vim}" "send-keys C-k" "select-pane -U"
bind-key -n C-l if -F "#{@pane-is-vim}" "send-keys C-l" "select-pane -R"

# Seamless resizing between tmux panes and Neovim windows
bind-key -n M-h if -F "#{@pane-is-vim}" "send-keys M-h" "resize-pane -L 3"
bind-key -n M-j if -F "#{@pane-is-vim}" "send-keys M-j" "resize-pane -D 3"
bind-key -n M-k if -F "#{@pane-is-vim}" "send-keys M-k" "resize-pane -U 3"
bind-key -n M-l if -F "#{@pane-is-vim}" "send-keys M-l" "resize-pane -R 3"

### Keymaps
# <C-b>c: create new window/tab
# <C-b>1: select window 1
# <C-b>2: select window 2
# <C-b>n: select next window
# <C-b>p: select previous window
# <C-b>,: rename current window
# <C-b>s: left/right split
# <C-b>S: upper/lower split
# <C-b>z: maximize/restore current pane
# <C-b>x: close current pane
# <C-b>&: close current window
# <C-b>d: detach from tmux

### Neovim-matched keymaps
# <C-h>: move focus left
# <C-j>: move focus down
# <C-k>: move focus up
# <C-l>: move focus right
# <M-h>: move divider left
# <M-j>: move divider down
# <M-k>: move divider up
# <M-l>: move divider right

# Reload this configuration
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux configuration reloaded"
